/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.ventanas;

import edu.cuc.palabras.LongitudIncorrectaException;
import edu.cuc.palabras.LongitudSinonimoIncorrectaException;
import edu.cuc.palabras.Palabra;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alexisdelahoz
 */
public class FrmPalabrasDialogo extends javax.swing.JDialog {

    private Palabra palabraNueva;

    /**
     * Creates new form FrmPalabras
     */
    public FrmPalabrasDialogo() {
        initComponents();
    }

    public FrmPalabrasDialogo(java.awt.Frame owner, Palabra palabraNueva, boolean modal) {
        super(owner, modal);
        initComponents();
        this.palabraNueva = palabraNueva;
        txtPalabra.setText(palabraNueva.getPalabra());
        //Actualizar lista
        actualizarListaSinonimos();
    }

    public Palabra getPalabraNueva() {
        return palabraNueva;
    }

    public void setPalabraNueva(Palabra palabraNueva) {
        this.palabraNueva = palabraNueva;
    }

    public void actualizarListaSinonimos() {
        //Actualizar Lista Sinonimos
        DefaultListModel<String> listado = palabraNueva.getListSinonimos();
        lstSinonimos.setModel(listado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSinonimo = new javax.swing.JTextField();
        cmdIngresarSinonimo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        cmdCantidad = new javax.swing.JButton();
        cmdPromedioLongitud = new javax.swing.JButton();
        cmdMayorLongitud = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSinonimos = new javax.swing.JList<String>();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Adiccionar Sinonimo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adiccion De Sinonimos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Palabra:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtPalabra.setOpaque(false);
        jPanel1.add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 420, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Sinónimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese sinónimo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtSinonimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSinonimo.setOpaque(false);
        txtSinonimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSinonimoKeyTyped(evt);
            }
        });
        jPanel2.add(txtSinonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 315, -1));

        cmdIngresarSinonimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490809916_Close.png"))); // NOI18N
        cmdIngresarSinonimo.setBorderPainted(false);
        cmdIngresarSinonimo.setContentAreaFilled(false);
        cmdIngresarSinonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarSinonimoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresarSinonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        cmdCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/cantidad32x32.png"))); // NOI18N
        cmdCantidad.setFocusable(false);
        cmdCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdCantidad.setOpaque(false);
        cmdCantidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdCantidad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdCantidadMouseMoved(evt);
            }
        });
        cmdCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCantidadActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdCantidad);

        cmdPromedioLongitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/promedio32x32.png"))); // NOI18N
        cmdPromedioLongitud.setFocusable(false);
        cmdPromedioLongitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdPromedioLongitud.setOpaque(false);
        cmdPromedioLongitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdPromedioLongitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdPromedioLongitudMouseMoved(evt);
            }
        });
        cmdPromedioLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPromedioLongitudActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdPromedioLongitud);

        cmdMayorLongitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/mayorque.png"))); // NOI18N
        cmdMayorLongitud.setFocusable(false);
        cmdMayorLongitud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdMayorLongitud.setOpaque(false);
        cmdMayorLongitud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdMayorLongitud.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdMayorLongitudMouseMoved(evt);
            }
        });
        cmdMayorLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorLongitudActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdMayorLongitud);

        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/delete-icon.png"))); // NOI18N
        cmdEliminar.setFocusable(false);
        cmdEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdEliminar.setOpaque(false);
        cmdEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdEliminarMouseMoved(evt);
            }
        });
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdEliminar);

        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/1490815099_Log Out.png"))); // NOI18N
        cmdSalir.setBorderPainted(false);
        cmdSalir.setContentAreaFilled(false);
        cmdSalir.setFocusable(false);
        cmdSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cmdSalirMouseMoved(evt);
            }
        });
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdSalir);

        jPanel3.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 35, 390, 52));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 500, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstSinonimos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstSinonimos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 189, 220));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 210, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 730, 290));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/ventanas/76111750-234F-4A6C-85C4-120D7400C6CE.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarSinonimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarSinonimoActionPerformed
        if (txtSinonimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adiccione Sinonimo", "Error", JOptionPane.ERROR_MESSAGE);
            txtSinonimo.requestFocusInWindow();
        } else {
            try {
                palabraNueva.adicionarConLongitud(new Palabra(txtSinonimo.getText()));
                txtSinonimo.setText(null);
                JOptionPane.showMessageDialog(this,
                        "Sinonimo ingresado!",
                        "Confirmación",
                        JOptionPane.INFORMATION_MESSAGE);
                //Actualizar Lista Sinonimos
                actualizarListaSinonimos();
            } catch (LongitudIncorrectaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmPalabrasDialogo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (LongitudSinonimoIncorrectaException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(FrmPalabrasDialogo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdIngresarSinonimoActionPerformed

    private void cmdCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCantidadActionPerformed
        JOptionPane.showMessageDialog(this,
                "La cantidad de sinonimos es: " + palabraNueva.cantidadSinonimos(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdCantidadActionPerformed

    private void cmdPromedioLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPromedioLongitudActionPerformed
        JOptionPane.showMessageDialog(this,
                "El promedio por longitud es: " + palabraNueva.promedioLongitud(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdPromedioLongitudActionPerformed

    private void cmdMayorLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorLongitudActionPerformed
        JOptionPane.showMessageDialog(this,
                "El sinonimo de mayor longitud es: " + palabraNueva.sinonimoMayorLongitud(),
                "Resultado",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdMayorLongitudActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        //Verificar la seleccion de la lista
        String elementoSeleccionado = lstSinonimos.getSelectedValue();
        if (elementoSeleccionado != null) {
            try {
                Palabra sinonimoAEliminar = new Palabra(elementoSeleccionado);
                palabraNueva.eliminarSinonimo(sinonimoAEliminar);
                //Actualizar Lista Sinonimos
                DefaultListModel<String> listado = palabraNueva.getListSinonimos();
                lstSinonimos.setModel(listado);
            } catch (LongitudIncorrectaException ex) {
                Logger.getLogger(FrmPalabras.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un sinónimo");
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSalirMouseMoved

        String Salir = "Boton Salir";
        cmdSalir.setToolTipText(Salir);
    }//GEN-LAST:event_cmdSalirMouseMoved

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed

        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?", "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdEliminarMouseMoved

        String Eliminar = "Boton Eliminar";
        cmdEliminar.setToolTipText(Eliminar);

    }//GEN-LAST:event_cmdEliminarMouseMoved

    private void cmdMayorLongitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdMayorLongitudMouseMoved

        String Mayor = "Boton Mayor Longitud";
        cmdMayorLongitud.setToolTipText(Mayor);
    }//GEN-LAST:event_cmdMayorLongitudMouseMoved

    private void cmdPromedioLongitudMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPromedioLongitudMouseMoved

        String Promedio = "Boton Promedio Longitud";
        cmdPromedioLongitud.setToolTipText(Promedio);
    }//GEN-LAST:event_cmdPromedioLongitudMouseMoved

    private void cmdCantidadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCantidadMouseMoved

        String Cantidad = "Boton Cantidad De Sinonimos";
        cmdPromedioLongitud.setToolTipText(Cantidad);  
    }//GEN-LAST:event_cmdCantidadMouseMoved

    private void txtSinonimoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSinonimoKeyTyped
        
        char c = evt.getKeyChar(); 
        
        if(!Character.isLetter(c)){ 
          getToolkit(); 
          evt.consume();  
        }
    }//GEN-LAST:event_txtSinonimoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCantidad;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdIngresarSinonimo;
    private javax.swing.JButton cmdMayorLongitud;
    private javax.swing.JButton cmdPromedioLongitud;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> lstSinonimos;
    private javax.swing.JTextField txtPalabra;
    private javax.swing.JTextField txtSinonimo;
    // End of variables declaration//GEN-END:variables
}
